apiVersion: v1
kind: Secret
metadata:
    name: ibindex-secret
    namespace: ibindex
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:YXI+5qdB,iv:BwckN5n8VjOYWybGF+p0FolF/LRtIBowwyZFgk1yWco=,tag:sh1hGAqt4IZ7ilMM1IsZHQ==,type:str]
    database-url: ENC[AES256_GCM,data:CAvGcfvtSOCgmojkRtVio0dUTI+IEuks+uGBb6U6HxwXxBT8eXdjQISX4DrMIpQOsA==,iv:/7xplZJ9ASeYMmuqPjM35j1OTrJ9BK+0ihXOxIw7Jyo=,tag:uflp3v8nx2013eTpXqe3kw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19fpxtk9nspxlukvn7jff2g2z0vy62kedrp6hcada28s2mjxrgfeqp8azln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweGVjOWdqbDhMRTBOdVg4
            b2RMRjJ0aVVHdGxIaTdjV1lIVnljajg0M0RNCjloMi9VeWpJVG0wVVh4ekdVZDNo
            NmZDOEp6Z1ZqN3JlS0MxS1Q1UTlRcTAKLS0tIFlnc3RoUk9FaWoyd3hCYnZSZlBr
            Q0V4OTdNNnFHdzUwYUtqQVg0R2NudTQKYC0GvN2IoRGZtei7Na/8fDip0RNs+3w3
            X3O422mvT5OIBzrh271v+LnqctV9ZnBz0PK5ibdgfWhotmITX+BDhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-18T19:10:11Z"
    mac: ENC[AES256_GCM,data:7I3XWp1qpz6P2w8a/5HVNiclOsq1jy8xCosNJyN4tC8MA9QTHjACpt5uLUklXtA0usXiJSFw2vMTYF+NwzMLATiNwK+2s9eamRFCjBli78yZYlFhZdIlIwXVtkp0GryuHKnjl/SP5fB5cMlVLDWX5yVUQPwVnEzOjFmyhW2jn4k=,iv:PGeP/8IrbuzIFsmD4lGKTS1JlNtI7q+wAlXycLJG2Ic=,tag:BkDAL1O+Zbf2b3KoqAmHUQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
